version: "2"
run:
  build-tags:
    - test
    - goexperiment.synctest
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - intrange
    - lll
    - loggercheck
    - maintidx
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    lll:
      # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
      line-length: 120
      # tab width in spaces. Default to 1.
      tab-width: 4
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: ^// @(component|componentprop)
      - linters:
          - lll
        path: (nil/services/cliservice/block_format_test.go|nil/services/cliservice/block.go)
      - linters:
          - lll
        path: nil/internal/abi/abi_test.go
        source: "^//\treceipt{status=1 cgas=23949"
      - linters:
          - lll
        path: nil/services/synccommittee/prover/internal/constants/proof_producer_codes.go
        source: ^// https://github.com/NilFoundation/placeholder/
      - linters:
          - lll
        path: nil/services/synccommittee/core/reset/resetter.go
        source: "^\t\t// https://www.notion.so/nilfoundation/"
    paths:
      - clickhouse
      - third_party$
      - builtin$
      - examples$
issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - clickhouse
      - third_party$
      - builtin$
      - examples$
