linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - intrange
    - loggercheck
    - maintidx
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint

linters-settings:
  testifylint:
    enable-all: true

  gosec:
    excludes:
      - G115

issues:
  exclude-dirs:
    - clickhouse

run:
  build-tags:
    - test
