name: Cluster CI

on:
  pull_request:
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nix_check:
    name: Test - ${{ matrix.check }}
    runs-on: ["self-hosted", "aws_autoscaling"]
    strategy:
      fail-fast: false
      matrix:
        check: ["ibft", "heavy", "nil", "nildocs", "niljs", "nilexplorer", "uniswap", "clijs"]
    steps:
      - name: checkout local actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run check
        run: nix build .#checks.x86_64-linux.${{ matrix.check == 'nil' && 'others' || matrix.check }} -L

  ensure_cluster_builds_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: aarch64
          - os: macos-13
            arch: x64
    environment: prod
    name: MacOS CI
    steps:
      - name: checkout local actions
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Golang and solc
        run: |
          brew update
          brew tap ethereum/ethereum
          brew install go solidity protobuf coreutils
          go install golang.org/x/tools/cmd/stringer@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: build binaries
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make

      - name: Upload nil binary as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: nil-darwin-${{ matrix.arch }}
          path: |
            build/bin/nil
